version: "3.8"

x-environment: &environment
  SERVER_HOST: 0.0.0.0
  REDIS_PUBSUB_CONNECTION_URL: redis://pubsub.redis:6378
  REDIS_CACHE_CONNECTION_URL: redis://db.redis:6379

services:
  db.redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379

  pubsub.redis:
    image: redis:6.0-alpine
    ports:
      - 6389:6379

  service.control-tower:
    build:
      context: .
      dockerfile: ./builds/service.control-tower/Dockerfile
    image: lab-automation-playground/service.control-tower:latest
    env_file:
      - ./services/control-tower/.env
    environment:
      <<: *environment

  service.data-gateway:
    build:
      context: .
      dockerfile: ./builds/service.data-gateway/Dockerfile
    image: lab-automation-playground/service.data-gateway:latest
    env_file:
      - ./services/data-gateway/.env
    environment:
      <<: *environment

  service.ot-builder:
    build:
      context: .
      dockerfile: ./builds/service.ot-builder/Dockerfile
    image: lab-automation-playground/service.ot-builder:latest
    ports:
      - 8000:8000
    environment:
      <<: *environment

  service.chibio-relay:
    build:
      context: .
      dockerfile: ./builds/service.chibio-relay/Dockerfile
    image: lab-automation-playground/service.chibio-relay:latest
    depends_on:
      - service.data-gateway
    environment:
      <<: *environment
      FORWARDER_DATA_GATEWAY_ADDR: service.data-gateway:8000
    volumes:
      - ./services/chibio-relay/test/data:/usr/service/data
