version: "3.8"

x-environment: &environment
  REDIS_CACHE_URL: redis://db.redis:6379
  REDIS_PUBSUB_URL: redis://pubsub.redis:6379
  FORWARDER_DATA_GATEWAY_URL: http://service.data-gateway:8000
  SERVER_HOST: 0.0.0.0

services:
  db.redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379

  pubsub.redis:
    image: redis:6.0-alpine
    ports:
      - 6389:6379

  service.control-tower:
    build:
      context: .
      dockerfile: ./docker/service.control-tower/Dockerfile
    image: lab-automation/service.control-tower:latest
    depends_on:
      - db.redis
      - pubsub.redis
    environment:
      <<: *environment
      PLUGIN_RIFFYN_API_KEY: ${RIFFYN_API_KEY}

  service.data-gateway:
    build:
      context: .
      dockerfile: ./docker/service.data-gateway/Dockerfile
    image: lab-automation/service.data-gateway:latest
    ports:
      - 9000:8000
    depends_on:
      - db.redis
      - pubsub.redis
      - service.control-tower
    ports:
      - 9000:8000
    environment:
      <<: *environment
      PLUGIN_RIFFYN_API_KEY: ${RIFFYN_API_KEY}
      PLUGIN_RIFFYN_CONTROL_TOWER_URL: http://service.control-tower:8000

  service.ot-builder:
    build:
      context: .
      dockerfile: ./docker/service.ot-builder/Dockerfile
    image: lab-automation/service.ot-builder:latest
    depends_on:
      - db.redis
      - pubsub.redis
      - service.control-tower
    ports:
      - 8000:8000
    environment:
      <<: *environment
